# Generated by Django 3.2.12 on 2022-11-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='info_img', verbose_name='img'),
        ),
    ]
