# Generated by Django 3.2.12 on 2023-01-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImgLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img_logo', verbose_name='img')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
