# Generated by Django 3.2.12 on 2023-01-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productimglogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Instock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=True),
        ),
    ]
