# Generated by Django 3.2.12 on 2023-01-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='visiable',
            field=models.BooleanField(default=False),
        ),
    ]
