# Generated by Django 3.2.12 on 2023-03-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
    ]
