# Generated by Django 3.2.12 on 2023-03-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_contactinfo_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='visible',
        ),
        migrations.AddField(
            model_name='faqinfo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
