# Generated by Django 3.2.12 on 2023-03-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_blogcomment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='author',
        ),
    ]
