# Generated by Django 3.2.12 on 2023-03-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_blogcomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.article'),
        ),
    ]
