# Generated by Django 3.2.12 on 2023-03-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_faqinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqinfo',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
