# Generated by Django 3.2.12 on 2023-03-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20230305_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
