# Generated by Django 3.2.12 on 2023-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_remove_blogcomment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='name_form',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
