# Generated by Django 3.2.12 on 2023-03-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20230311_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='specification_value',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='specification',
            field=models.CharField(max_length=50),
        ),
    ]
