# Generated by Django 3.2.12 on 2023-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_alter_productspecification_specification_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.TextField(),
        ),
    ]
