# Generated by Django 4.0 on 2022-10-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='OrderStatus',
        ),
    ]
